name: Bug Report
description: File a bug report.
title: "[Bug]: "
body:
  - type: markdown
    attributes:
      value: |
        Please be descriptive about your system and setup, as well as describe the bug as well as you can. Thank you for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more information? This is optional.
      placeholder: email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Tell us what happened and what you expected to happen.
      placeholder: Tell us everything you know about the bug!
      value: "A bug happened! It [blank]ed when it should have [blank]ed."
    validations:
      required: true
